// Code generated by sqlc. DO NOT EDIT.
// source: cocktail.sql

package db

import (
	"context"
	"database/sql"
)

const createCocktail = `-- name: CreateCocktail :one
INSERT INTO cocktail (
  recipe_id, ingredient_id, measurement_qty_id, measurement_units_id
) VALUES (
  $1, $2, $3, $4
)
RETURNING cocktail_id, recipe_id, ingredient_id, measurement_qty_id, measurement_units_id
`

type CreateCocktailParams struct {
	RecipeID           int64         `json:"recipe_id"`
	IngredientID       int64         `json:"ingredient_id"`
	MeasurementQtyID   sql.NullInt64 `json:"measurement_qty_id"`
	MeasurementUnitsID sql.NullInt64 `json:"measurement_units_id"`
}

func (q *Queries) CreateCocktail(ctx context.Context, arg CreateCocktailParams) (Cocktail, error) {
	row := q.db.QueryRowContext(ctx, createCocktail,
		arg.RecipeID,
		arg.IngredientID,
		arg.MeasurementQtyID,
		arg.MeasurementUnitsID,
	)
	var i Cocktail
	err := row.Scan(
		&i.CocktailID,
		&i.RecipeID,
		&i.IngredientID,
		&i.MeasurementQtyID,
		&i.MeasurementUnitsID,
	)
	return i, err
}

const deleteCocktail = `-- name: DeleteCocktail :exec
DELETE FROM cocktail
WHERE cocktail_id = $1
`

func (q *Queries) DeleteCocktail(ctx context.Context, cocktailID int64) error {
	_, err := q.db.ExecContext(ctx, deleteCocktail, cocktailID)
	return err
}

const getCocktail = `-- name: GetCocktail :one
SELECT cocktail_id, recipe_id, ingredient_id, measurement_qty_id, measurement_units_id FROM cocktail
WHERE cocktail_id = $1 LIMIT 1
`

func (q *Queries) GetCocktail(ctx context.Context, cocktailID int64) (Cocktail, error) {
	row := q.db.QueryRowContext(ctx, getCocktail, cocktailID)
	var i Cocktail
	err := row.Scan(
		&i.CocktailID,
		&i.RecipeID,
		&i.IngredientID,
		&i.MeasurementQtyID,
		&i.MeasurementUnitsID,
	)
	return i, err
}

const listCocktails = `-- name: ListCocktails :many
SELECT cocktail_id, recipe_id, ingredient_id, measurement_qty_id, measurement_units_id FROM cocktail
ORDER BY cocktail_id
LIMIT $1
OFFSET $2
`

type ListCocktailsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCocktails(ctx context.Context, arg ListCocktailsParams) ([]Cocktail, error) {
	rows, err := q.db.QueryContext(ctx, listCocktails, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cocktail
	for rows.Next() {
		var i Cocktail
		if err := rows.Scan(
			&i.CocktailID,
			&i.RecipeID,
			&i.IngredientID,
			&i.MeasurementQtyID,
			&i.MeasurementUnitsID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCocktail = `-- name: UpdateCocktail :one
UPDATE cocktail
  set recipe_id = $2,
    ingredient_id = $3,
    measurement_qty_id = $4,
    measurement_units_id = $5
WHERE cocktail_id = $1
RETURNING cocktail_id, recipe_id, ingredient_id, measurement_qty_id, measurement_units_id
`

type UpdateCocktailParams struct {
	CocktailID         int64         `json:"cocktail_id"`
	RecipeID           int64         `json:"recipe_id"`
	IngredientID       int64         `json:"ingredient_id"`
	MeasurementQtyID   sql.NullInt64 `json:"measurement_qty_id"`
	MeasurementUnitsID sql.NullInt64 `json:"measurement_units_id"`
}

func (q *Queries) UpdateCocktail(ctx context.Context, arg UpdateCocktailParams) (Cocktail, error) {
	row := q.db.QueryRowContext(ctx, updateCocktail,
		arg.CocktailID,
		arg.RecipeID,
		arg.IngredientID,
		arg.MeasurementQtyID,
		arg.MeasurementUnitsID,
	)
	var i Cocktail
	err := row.Scan(
		&i.CocktailID,
		&i.RecipeID,
		&i.IngredientID,
		&i.MeasurementQtyID,
		&i.MeasurementUnitsID,
	)
	return i, err
}
