// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Cocktail struct {
	CocktailID         int64
	RecipeID           int64
	IngredientID       int64
	MeasurementQtyID   sql.NullInt64
	MeasurementUnitsID sql.NullInt64
}

type Ingredient struct {
	IngredientID   int64
	IngredientName string
}

type MeasurementQty struct {
	MeasurementQtyID int64
	QtyAmount        int64
}

type MeasurementUnit struct {
	MeasurementUnitsID int64
	Unit               string
}

type Recipe struct {
	RecipeID     int64
	DrinkName    string
	Instructions string
	ImageUrl     sql.NullString
	CreatedAt    time.Time
}
