// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Cocktail struct {
	CocktailID         int64 `json:"cocktail_id"`
	RecipeID           int64 `json:"recipe_id"`
	IngredientID       int64 `json:"ingredient_id"`
	MeasurementQtyID   int64 `json:"measurement_qty_id"`
	MeasurementUnitsID int64 `json:"measurement_units_id"`
}

type Ingredient struct {
	IngredientID   int64  `json:"ingredient_id"`
	IngredientName string `json:"ingredient_name"`
}

type MeasurementQty struct {
	MeasurementQtyID int64 `json:"measurement_qty_id"`
	QtyAmount        int64 `json:"qty_amount"`
}

type MeasurementUnit struct {
	MeasurementUnitsID int64  `json:"measurement_units_id"`
	Unit               string `json:"unit"`
}

type Recipe struct {
	RecipeID     int64     `json:"recipe_id"`
	DrinkName    string    `json:"drink_name"`
	Instructions string    `json:"instructions"`
	ImageUrl     *string   `json:"image_url"`
	CreatedAt    time.Time `json:"created_at"`
}
