// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Cocktail struct {
	CocktailID   int64
	DrinkName    string
	Instructions string
	ImageUrl     sql.NullString
	CreatedAt    time.Time
}

type Ingredient struct {
	IngredientID   int64
	IngredientName string
}

type IngredientsToCocktail struct {
	CocktailID         int64
	IngredientID       int64
	MeasurementQtyID   sql.NullInt64
	MeasurementUnitsID sql.NullInt64
}

type MeasurementQty struct {
	MeasurementQtyID int64
	QtyAmount        sql.NullInt64
}

type MeasurementUnit struct {
	MeasurementUnitsID int64
	Unit               sql.NullString
}
